#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commit_message_file="$1"
commit_message=$(cat "$commit_message_file")

echo "Commit message: $commit_message"

# Add your validation logic here
if [ -z "$commit_message" ]; then
  echo "Error: Commit message cannot be empty"
  exit 1
fi

# set up env
pip install venv
source venv/bin/activate
pip install -r $(pwd)/.husky/requirements.txt

python $(pwd)/.husky/validate-issue.py --message commit_message