name: Build and Test Go Binary

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22


      - name: Get make
        working-directory: ghrunner
        run: |
              sudo apt-get update
              sudo apt-get install make

      - name: Run make test
        run: make test
        working-directory: ghrunner
