name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

        - name: Install Husky
          run: npm install husky

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.8
            cache: 'pip'
        - run: pip install -r .husky/requirements.txt

        - name: Run valide commit message
          run: python .husky/validate-issue.py --message "${{ github.event.head_commit.message }}"
