name: Verify Pre Commit Standards

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

        - name: Install Husky
          run: npm install husky

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.8
            cache: 'pip'
        - run: pip install -r .husky/requirements.txt

        - name: Environment variables
          run: echo "GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV

        - name: Run validation commit message
          run: python .husky/validate-issue.py --message "${{ github.event.head_commit.message }}"

        - name: Run conventional commit hook
          run: |
            if ! echo "${{ github.event.head_commit.message }}" | grep -q ":"; then
                echo "Aborting commit. Conventional commit must be followed by a ':'. For example, 'chore: typo #4'" >&2
                exit 1
            fi
            if !  echo "${{ github.event.head_commit.message }}" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|BREAKING CHANGE)(\(.+?\))?: .{1,}$"; then
                echo "Aborting commit with $temp. Must use conventional commit. https://www.conventionalcommits.org/en/v1.0.0/" >&2
                exit 1
            fi
            if ! echo "${{ github.event.head_commit.message }}" | grep -qE "^.{1,88}$"; then
                echo "Aborting commit. Your commit message is too long." >&2
                exit 1
            fi