name: Release

on:
    push:
        branches:
            - fetch-depth
jobs:
    release:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
              with:
               fetch-depth: 0  # Fetch all history for all tags and branches
            - name: Set up Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
              with:
               node-version: '20.8.1'
            - run: npx semantic-release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}