name: Release

on:
    push:
        branches:
            - semantic-releases
jobs:
    release:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
            - run: npm ci
            - run: npx semantic-release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}