name: Verify Lint and Format

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

# Workflow verifies code aheres to linting and formatting standards.

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

            - name: Change into directory
              run: cd ghrunner

            - name: Set up Go
              uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1

              with:
                go-version: 1.22

            - name: Get make
              run: |
                    sudo apt-get update
                    sudo apt-get install make

            - name: Run go lint
              run: |
                cd ghrunner
                make lint

            - name: Run gofmt
              id: gofmt
              run: |
                    cd ghrunner
                    diff=$(gofmt -l -s -d .)
                    if [ -n "$diff" ]; then
                    echo "Files are not formatted:"
                    echo "$diff"
                    exit 1
                    else
                    echo "All files are properly formatted."
                    fi

